name: Deploy Supabase Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ] || [ -z "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN or SUPABASE_PROJECT_REF" >&2
            exit 1
          fi

      - name: Set Edge Function Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} \
            "PROJECT_URL=${{ secrets.PROJECT_URL }}" \
            "SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }}"
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          fi
          if [ -n "${{ secrets.TAVILY_API_KEY }}" ]; then
            supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}"
          fi

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy users updatePassword assistant --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
