name: Deploy Supabase Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set Edge Function Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} \
            "PROJECT_URL=${{ secrets.PROJECT_URL }}" \
            "SERVICE_ROLE_KEY=${{ secrets.SERVICE_ROLE_KEY }}"

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy users updatePassword --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
